foodrecipe/main/urls.py
from django.urls import path
from . import views
from .views import update_recipe, recipe_list

app_name= 'main'
urlpatterns = [
    path('', views.home, name="Homepage"),
    path('register/', views.register, name= 'register'),
    path('index/', views.home, name='Homepage'),
    path('login/', views.Login, name='login'),
    path('logout/', views.Logout, name='logout'),
    path('uploaded/', views.recipe_list, name="recipe_list"),
    path('recipe/upload/', views.upload_recipe, name='upload'),
    path('additems/', views.add_items, name = 'additems'),
    path('blog/', views.blog, name = 'blog'),
    path('uploaded/<int:pk>/', views.delete_recipe, name='delete_recipe'),
    # path('uploaded/update_recipe/<int:item_id>/', views.update_recipe, name='update_recipe'),
    path('uploaded/update_recipe/<int:id>/', update_recipe.as_view(), name='update_recipe'),
    path('recipe_list/', views.recipe_list, name='recipe_list'),

]

foodrecipe/recipe_download/urls.py
from django.urls import path
from . import views

app_name= 'recipe_download'
urlpatterns = [

    path('browse/', views.browse, name="browse"),
    path('upload_video/', views.upload_video, name ="upload_video"),

]

foodrecipe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('main.urls')),
    path('', include('feedback.urls')),
    path('', include('restapi.urls')),
    path('', include('recipe_download.urls')),
    path('admin/', admin.site.urls),
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

foodrecipe/templates/base.html
 <!DOCTYPE html>
 <html lang="zxx">
 
 <head>
     <meta charset="UTF-8">
     <meta name="description" content="Yoga Studio Template">
     <meta name="keywords" content="Yoga, unica, creative, html">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <meta http-equiv="X-UA-Compatible" content="ie=edge">
     <title>Flamingo | Food Recipe</title>
 
     <!-- Google Font -->
     <link href="https://fonts.googleapis.com/css?family=PT+Sans:400,700&display=swap" rel="stylesheet">
 
     <!-- Css Styles -->
     <link rel="stylesheet" href="/static/css/bootstrap.min.css" type="text/css">
     <link rel="stylesheet" href="/static/css/font-awesome.min.css" type="text/css">
     <link rel="stylesheet" href="/static/css/nice-select.css" type="text/css">
     <link rel="stylesheet" href="/static/css/slicknav.min.css" type="text/css">
     <link rel="stylesheet" href="/static/css/style.css" type="text/css">
 </head>

 <body>
     
  <!-- Page Preloder -->
     <div id="preloder">
        <div class="loader">

        </div>

      </div>
      <body>
  
        <!-- Header Section Begin -->
          <header class="header-section">
              <div class="container">
                  <div class="logo">
                      <a href="{% url 'main:blog' %}"><img src="/static/img/logo_recipe.png" alt="logo"></a>
                  </div>
                  <div class="nav-menu">
                      <nav class="main-menu mobile-menu">
                          <ul>
                              <li><a href="{% url 'main:blog' %}">Home</a></li>
                              <li><a href="#">Pages</a>
                                  <ul class="sub-menu">
                                      <li><a href="{% url 'main:additems' %}">Add an item</a></li>
                                      <li><a href="{% url 'main:Homepage' %}">Info</a></li>
                                      <li><a href="{% url 'contact' %}">Contact</a></li>
                                      <li><a href="{% url 'main:upload' %}">Upload Recipe</a></li>
                                      <li><a href="{% url 'recipe_download:upload_video' %}">Upload Video</a></li>
                                      <li><a href="{% url 'main:recipe_list' %}">Recipe Uploaded</a></li>
                                      <li><a href="{% url 'recipe_download:browse' %}">Downloads</a></li>
                                      
                                  </ul>
                              </li>
                              {% if user.is_authenticated %}
                              <li class="active"><a href="{% url 'main:register' %}">Hi, {{user.email}}</a></li>
                              <li><a href="{% url 'main:logout' %}">Log out</a></li>
                              
                              {% else %}
                              <li><a href="/register">Sign Up</a></li>
                              <li><a href="/login">Login</a></li>
                              {% endif %}
                            </ul>                         
                      </nav>
                      <div class="nav-right search-switch">
                          <i class="fa fa-search"></i>
                      </div>
                  </div>
                  <div id="mobile-menu-wrap"></div>
              </div>
          </header>
          <!-- Header End -->

          <!--Body-->
          {% block content %}

          {% endblock %}
          <!--Body ends here-->


          <!--Using include element for urls pattern-->
          
          {% include 'footer.html' %}
          
          <!--include url pattern for footer only-->
      

  <!-- Search model -->
<div class="search-model">
  <div class="h-100 d-flex align-items-center justify-content-center">
    <div class="search-close-switch">+</div>
    <form class="search-model-form" method="GET">
      <input type="text" id="search" placeholder="Search here....." name="q">
    </form>
  </div>
</div>
<!-- Search model end -->

  <!-- Js Plugins -->
  <script src="/static/js/jquery-3.3.1.min.js"></script>
  <script src="/static/js/bootstrap.min.js"></script>
  <script src="/static/js/jquery.slicknav.js"></script>
  <script src="/static/js/jquery.nice-select.min.js"></script>
  <script src="/static/js/mixitup.min.js"></script>
  <script src="/static/js/main.js"></script>
 </body>
 </html>