foodrecipe/main/urls.py
from django.urls import path
from . import views
from .views import update_recipe, recipe_list

app_name= 'main'
urlpatterns = [
    path('', views.home, name="Homepage"),
    path('register/', views.register, name= 'register'),
    path('index/', views.home, name='Homepage'),
    path('login/', views.Login, name='login'),
    path('logout/', views.Logout, name='logout'),
    path('uploaded/', views.recipe_list, name="recipe_list"),
    path('recipe/upload/', views.upload_recipe, name='upload'),
    path('additems/', views.add_items, name = 'additems'),
    path('blog/', views.blog, name = 'blog'),
    path('uploaded/<int:pk>/', views.delete_recipe, name='delete_recipe'),
    # path('uploaded/update_recipe/<int:item_id>/', views.update_recipe, name='update_recipe'),
    path('uploaded/update_recipe/<int:id>/', update_recipe.as_view(), name='update_recipe'),
    path('recipe_list/', views.recipe_list, name='recipe_list'),

]

foodrecipe/main/templates/main/Adding_items.html
{% extends 'base.html' %}

{% load crispy_forms_tags %} 

   {% block content %}

    <!-- Adding item Section Begin -->
    <section class="contact-section spad">
         <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h3>Adding an item for recipe</h3>
                        
                    <form method="POST">
                       
                        {% csrf_token %} 

                        {{form|crispy}}
                       
                        <button type="submit" class="btn btn-primary">Add</button>
                    </form>
                </div>
            </div>
        </div> 
    </section> 
    <!-- Addding item Section End -->

    <!-- Similar Recipe Section Begin -->
    <section class="similar-recipe spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="similar-item">
                        <a href="#"><img src="/static/img/cat-feature/small-7.jpg" alt=""></a>
                        <div class="similar-text">
                            <div class="cat-name">Vegan</div>
                            <h6>Italian Tiramisu with Coffe</h6>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="similar-item">
                        <a href="#"><img src="/static/img/cat-feature/small-6.jpg" alt=""></a>
                        <div class="similar-text">
                            <div class="cat-name">Vegan</div>
                            <h6>Dry Cookies with Corn</h6>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="similar-item">
                        <a href="#"><img src="/static/img/cat-feature/small-5.jpg" alt=""></a>
                        <div class="similar-text">
                            <div class="cat-name">Vegan</div>
                            <h6>Asparagus with Pork Loin and Vegetables</h6>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="similar-item">
                        <a href="#"><img src="/static/img/cat-feature/small-4.jpg" alt=""></a>
                        <div class="similar-text">
                            <div class="cat-name">Vegan</div>
                            <h6>Smoked Salmon mini Sandwiches with Onion</h6>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Similar Recipe Section End -->

    {% endblock %}

  

foodrecipe/main/templates/main/blog.html
{% extends 'base.html' %}

{% block content %}
 
<!-- Comment Section Begin -->
    <section class="blog-section spad">
        
        <div class="container">
           
            {% for i in blog %}
            <hr>
            <strong>Item : </strong> {{i.item_title}}<br> 
            
            <form method="POST">
                {% csrf_token %}
                <input type="hidden" name="tenzin" value="{{i.id}}">
                <input type="text" name="msg"  placeholder="Write a comment...">
                <button type="submit" class="btn btn-primary">Comment</button>
            </form>
            <br>
           {% for comment in i.comments.all%}
           <div class="card" style="width: 15rem;">
            <ul class="list-group list-group-flush">
              <li class="list-group-item">{{comment.msg}}</li>
              <li class="list-group-item">No. of comments: {{i.comments.count}}</li>
            </ul>
            </div>
            {% endfor %}
            {% endfor %}
        </div>
    
    </section>
    <!-- Comment Section End -->

    <!-- Similar Recipe Section Begin -->
    <section class="similar-recipe spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="similar-item">
                        <a href="#"><img src="/static/img/cat-feature/small-7.jpg" alt=""></a>
                        <div class="similar-text">
                            <div class="cat-name">Vegan</div>
                            <h6>Italian Tiramisu with Coffe</h6>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="similar-item">
                        <a href="#"><img src="/static/img/cat-feature/small-6.jpg" alt=""></a>
                        <div class="similar-text">
                            <div class="cat-name">Vegan</div>
                            <h6>Dry Cookies with Corn</h6>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="similar-item">
                        <a href="#"><img src="/static/img/cat-feature/small-5.jpg" alt=""></a>
                        <div class="similar-text">
                            <div class="cat-name">Vegan</div>
                            <h6>Asparagus with Pork Loin and Vegetables</h6>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="similar-item">
                        <a href="#"><img src="/static/img/cat-feature/small-4.jpg" alt=""></a>
                        <div class="similar-text">
                            <div class="cat-name">Vegan</div>
                            <h6>Smoked Salmon mini Sandwiches with Onion</h6>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Similar Recipe Section End -->
    
    {% endblock %}
    
   

foodrecipe/main/templates/main/index.html
{% extends 'base.html' %}

    {% block content %}

    <!-- Page Top Recipe Section Begin -->
    <section class="page-top-recipe">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 order-lg-2">
                    <div class="pt-recipe-item large-item">
                        <div class="pt-recipe-img set-bg" data-setbg="/static/img/recipe-3.jpg">
                            <i class="fa fa-plus"></i>
                        </div>
                        <div class="pt-recipe-text">
                            <span>March 10, 2019</span>
                            <h3>Cannellini Aglio e Olio with Salmon</h3>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 order-lg-1">
                    <div class="pt-recipe-item">
                        <div class="pt-recipe-img set-bg" data-setbg="/static/img/recipe-1.jpg">
                            <i class="fa fa-plus"></i>
                        </div>
                        <div class="pt-recipe-text">
                            <h4>Raw Vegan Carrot Cake Bites with Avocado</h4>
                        </div>
                    </div>
                    <div class="pt-recipe-item">
                        <div class="pt-recipe-img set-bg" data-setbg="/static/img/recipe-2.jpg">
                            <i class="fa fa-plus"></i>
                        </div>
                        <div class="pt-recipe-text">
                            <h4>One Pot Weeknight Lasagna Soup Recipe</h4>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 order-lg-3">
                    <div class="pt-recipe-item">
                        <div class="pt-recipe-img set-bg" data-setbg="/static/img/recipe-4.jpg">
                            <i class="fa fa-plus"></i>
                        </div>
                        <div class="pt-recipe-text">
                            <h4>Beef Burger with French Fries and Salad</h4>
                        </div>
                    </div>
                    <div class="pt-recipe-item">
                        <div class="pt-recipe-img set-bg" data-setbg="/static/img/recipe-5.jpg">
                            <i class="fa fa-plus"></i>
                        </div>
                        <div class="pt-recipe-text">
                            <h4>Raspberry Pancakes with Honey and Butter</h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Page Top Recipe Section End -->

    
    <!-- Categories Filter Section Begin -->
    <div class="categories-filter-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="filter-item">
                        <ul>
                            <li class="active" data-filter="*">Vegetarian</li>
                            <li data-filter=".mostpopular">Most popular</li>
                            <li data-filter=".meatlover">Meat Lover</li>
                            <li data-filter=".glutenfree">Gluten Free</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="cf-filter" id="category-filter">
                <div class="cf-item mix all mostpopular">
                    <div class="cf-item-pic">
                        <a href="{{static.urls}}" ><img src="/static/img/cate-filter/cate-filter-1.jpg" alt=""></a>
                    </div>
                    <div class="cf-item-text">
                        <h5>Sunday Brunch: Spaghetti and Eggs Recipe</h5>
                    </div>
                </div>
                <div class="cf-item mix all mostpopular">
                    <div class="cf-item-pic">
                        <img src="/static/img/cate-filter/cate-filter-2.jpg" alt="">
                    </div>
                    <div class="cf-item-text">
                        <h5>Sunday Brunch: Spaghetti and Eggs Recipe</h5>
                    </div>
                </div>
                <div class="cf-item mix all meatlover mostpopular">
                    <div class="cf-item-pic">
                        <img src="/static/img/cate-filter/cate-filter-3.jpg" alt="">
                    </div>
                    <div class="cf-item-text">
                        <h5>Sunday Brunch: Spaghetti and Eggs Recipe</h5>
                    </div>
                </div>
                <div class="cf-item mix all meatlover">
                    <div class="cf-item-pic glutenfree">
                        <img src="/static/img/cate-filter/cate-filter-4.jpg" alt="">
                    </div>
                    <div class="cf-item-text">
                        <h5>Sunday Brunch: Spaghetti and Eggs Recipe</h5>
                    </div>
                </div>
                <div class="cf-item mix all meatlover glutenfree">
                    <div class="cf-item-pic">
                        <img src="/static/img/cate-filter/cate-filter-5.jpg" alt="">
                    </div>
                    <div class="cf-item-text">
                        <h5>Sunday Brunch: Spaghetti and Eggs Recipe</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Categories Filter Section End -->

    
    <!-- Feature Recipe Section Begin -->
    <section class="feature-recipe">
        <div class="section-title">
            <h5>Featured Recipes</h5>
        </div>
        <div class="container po-relative">
            <div class="plus-icon">
                <i class="fa fa-plus"></i>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="fr-item">
                        <div class="fr-item-img">
                            <img src="/static/img/feature-1.jpg" alt="">
                        </div>
                        <div class="fr-item-text">
                            <h4>Sunday Brunch: Spaghetti and Eggs Recipe</h4>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="fr-item">
                        <div class="fr-item-img">
                            <img src="/static/img/feature-2.jpg" alt="">
                        </div>
                        <div class="fr-item-text">
                            <h4>Sunday Brunch: Spaghetti and Eggs Recipe</h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Feature Recipe Section End -->

    {% endblock %}
</body>

</html>

foodrecipe/main/templates/main/login.html
{% extends 'base.html'%}
  
{% load crispy_forms_tags %}       

{% block content %}

  <div class="container">
    <form method="POST">

      {% csrf_token %}
      
      {{form|crispy}}
    
      <button style="color: blue" type="submit">Login</button>

  
    </form>
  </div>

{% endblock %}
    
</body>
</html>

foodrecipe/main/templates/main/recipe_list.html
{% extends "base.html" %}

{% block content %}

<body>
  <div class="container">
  <div class="row row-cols-1 row-cols-md-2">
    {% for r in recipes  %}
    <div class="col-md-4">
      <div class="card">
        <img src="{{  r.recipe_image.url }}"  class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title"><strong>Item: </strong>{{r.item}}</h5>
          <h6 class="card-title"><strong>Recipe Title: </strong> {{r.recipe_title}}</h6>
          <h6 class="card-title"><strong>Category: </strong> {{r.recipe_category}}</h6>
          <p class="card-text"><strong>Description: </strong> {{r.recipe_description}}</p>
          <p class="card-text"><small class="text-muted"><strong>Posted on: </strong> {{r.date_time}}</small></p>
          <div class="row">
            <div>
            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Are you sure?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                    <div class="modal-body">
                      <form method="POST" action="{% url 'main:delete_recipe' r.pk  %}">
                      
                        {% csrf_token %}

                      <button type="submit" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal" name="delete" style='width:100px;margin-left:200px;'>YES</button>
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">NO</button>  
                    </form>
                    </div>
                      <div class="modal-footer">
                        <p>It will be permanently deleted from Recipe list.</p>
                  </div>
                </div>
              </div>
            </div>
            
            <a href="{% url 'main:update_recipe' r.pk%}" class="card-link text-success"style='width:100px;margin-buttom:40px;'>Update</a>
            <button type="button"  class="btn btn-danger" data-toggle="modal" data-target="#exampleModal"  data-dismiss="modal">delete</button>
            
            </div>      

        </div>

        </div>
      
      </div>
    
    </div>  
{% endfor %} 
  </div>
</div>

</body>
{% endblock %}

            
      

       

            

foodrecipe/main/templates/main/register.html
{% extends 'base.html' %}

{% block content %}

<div class="container p-3 my-3 bg-dark text-white">
<form method = 'POST'>

    {% csrf_token %}

    {{form.as_p}}
    <br>

    <button type="submit" class="btn btn-primary">Register</button>
</form>
</div>
{% endblock %}

foodrecipe/main/templates/main/update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

	<div class="container">
		<h2>Update Recipe</h2>
		<br> 
 		<form method="POST"  enctype="multipart/form-data">
 			{% csrf_token %}
	 
	 		{{form|crispy}}

 			<button type="submit" class="btn btn-primary">Update</button>
 		</form>
	</div>

{% endblock %}

foodrecipe/main/templates/main/upload_recipe.html
{% extends "base.html" %}

{% load crispy_forms_tags %}   

{% block content %}

	<div class="container">
		<h2>Upload recipe</h2>
		<br> 
 		<form method="POST"  enctype="multipart/form-data">
 			{% csrf_token %}
	 
			{{form|crispy}}

 			<button type="submit" class="btn btn-primary">Upload Recipe</button>
 		</form>
	</div>

{% endblock %}